# Generated by Django 4.2 on 2023-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='some_file',
            field=models.FileField(blank=True, null=True, upload_to='a_dir'),
        ),
    ]
