# Generated by Django 4.2 on 2023-05-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_some_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='some_file',
            field=models.FileField(blank=True, null=True, upload_to='b_dir'),
        ),
    ]
